# syntax=docker/dockerfile:1
FROM golang:1.23-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o wb-producer ./cmd/producer/st_prod.go

# Final image
FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/wb-producer .
COPY .env .env

CMD ["./wb-producer"]