version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: wb_user
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: wb_demo_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data


  migrate:
    image: migrate/migrate
    depends_on:
      - postgres
    volumes:
      - ./migrations:/migrations
    entrypoint: [
      "migrate",
      "-path", "/migrations",
      "-database", "postgres://wb_user:12345678@postgres:5432/wb_demo_db?sslmode=disable"
    ]
  kafka:
    image: bitnami/kafka:3.7
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_LOG_DIRS=/tmp/kafka-logs
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/bitnami/kafka

  wb-service:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - kafka
    environment:
      - HTTP_HOST=0.0.0.0
      - HTTP_PORT=8081
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=wb_user
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DATABASE=wb_demo_db
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092
      - KAFKA_GROUP=wb-tech-demo-service
    ports:
      - "8081:8081"

  wb-producer:
    build:
      context: .
      dockerfile: Dockerfile.producer
    depends_on:
      - kafka


volumes:
  pgdata:
  kafka_data: